### ISSUE TITLE
Importing from across folders

### ISSUE THREAD

**Issue by haopei** [droot/gae-boilerplate#2]
Thank you for creating this project. I've learned a lot about project structure. I would like to know how we might import modules between folders? Given the current directory structure, how might we import models/models.py into handlers/common_handler.py?

**Comment by ajnisbet** [comment]
I set it up similarly to the handlers folder.

Say you define a model `User` in models/auth.py. If you add `from auth import *` to models/__init__.py, you can do `from models import User` in handlers/common_handler.py.
